---
# 
company: spacelift

# Market breadth reader
stockList:
  - name: hkex
    desc: Hong Kong Stock Exchange
    link: https://www.hkex.com.hk/eng/services/trading/securities/securitieslists/ListOfSecurities.xlsx

# Indexs / exchanges / portfolios / sectors / themes
indexes:
  - name: IXIC
    breadth: $NAA20R,$NAA50R,$NAA150R,$NAA200R
    stockCode: $COMPQ
    tradingViewCode: NDX
  - name: DJI
    breadth: $DOWA20R,$DOWA50R,$DOWA150R,$DOWA200R
    stockCode: $INDU
    tradingViewCode: DJI
  - name: GSPC
    breadth: $SPXA20R,$SPXA50R,$SPXA150R,$SPXA200R
    stockCode: $SPX
    tradingViewCode: SPX

exchanges:
  - name: NIM
    tradingView: NASDAQ
  - name: PCX
    tradingView: AMEX
  - name: NYQ
    tradingView: NYSE
  - name: NMS
    tradingView: NASDAQ
  - name: NGM
    tradingView: NASDAQ
  - name: BTS
    tradingView: AMEX
  - name: DJI
    tradingView: TVC
  - name: SNP
    tradingView: TVC

portfolios:
    #
    # CELEBRITY
    #
  - desc: Warren-Buffett
    chartDataSource: SC
    category: US-CELEBRITY
    data: AAPL,BAC,AXP,KO,CVX,OXY,KHC,MCO,CB,DVA,C,KR,VRSN,V,AMZN,MA,LSXMK,NU,COF,AON,ALLY,CHTR,TMUS,LSXMA,LPX,LLYVK,FND,SIRI,ULTA,LLYVA,HEIA,NVR,DEO,LILA,JEF,VOO,SPY,LENB,LILAK,BATRK
    id: berkshire-hathaway-inc
  - desc: Michael-Burry
    chartDataSource: SC  
    category: US-CELEBRITY
    data: BABA,FOUR,MOH,BIDU,JD,HPP,REAL,ACIC,OLPX,BCAB
    id: scion-asset-management-llc
  - desc: Stanley-Druckenmiller
    chartDataSource: SC  
    category: US-CELEBRITY
    data: COHR,CPNG,VST,NTRA,STX,MSFT,WWD,KMI,MAA,PM,ZI,TECK,CPT,FLUT,MELI,FCX,OPCH,GEV,FLEX,SWTX,DAKT,PANW,NVDA,WAB,MSGE,BCS,DFS,ADBE,PLTR,NWSA,ANET,NWS,ARGT,BMA,GGAL,CRNX,BAH,YPF,IQV,LYV,WULF,CNK,SLN,VCYT,AES,AAPL,TPX,LBTYA,SE,LBTYK,EQT,SPHR,ACLX,BLDR,BCYC,IHS,TLSI,GPCR,INSM,TEO,NRIX,IVVD,JOBY
    id: duquesne-family-office-llc
  - desc: David Tepper
    chartDataSource: SC  
    category: US-CELEBRITY  
    data: GM,GOOG,DAL,HCA,WHR,LUV,ALL,SXL,OC,KMI,BKNG,AAPL,AY,HUN,PFE,PPG,AMLP,GT,NXPI,WPZ,IR,HPE,URI,CBI,EMN,COOP,RRC,TGI,UAL,SWN,CYH,COG,FCX,KYN,EQT,EXP,AR,TOO,SPY,TGP,TYG,XCEMX,CWEN,BAC,LEN,RF,DHI,MAS,BABA,MHK
    id: appaloosa-management-lp
    #
    # US INDEX
    #
  - desc: DOW30
    chartDataSource: SC
    category: US-INDEX
    data: AMZN,AXP,AMGN,AAPL,BA,CAT,CSCO,CVX,GS,HD,HON,IBM,INTC,JNJ,KO,JPM,MCD,MMM,MRK,MSFT,NKE,PG,TRV,UNH,CRM,VZ,V,WMT,DIS,DOW 
  - desc: NQ100
    chartDataSource: SC
    category: US-INDEX
    data: ADBE,ADP,ABNB,GOOGL,GOOG,AMZN,AMD,AEP,AMGN,ADI,ANSS,AAPL,AMAT,ASML,AZN,TEAM,ADSK,BKR,BIIB,BKNG,AVGO,CDNS,CDW,CHTR,CTAS,CSCO,CCEP,CTSH,CMCSA,CEG,CPRT,CSGP,COST,CRWD,CSX,DDOG,DXCM,FANG,DLTR,DASH,EA,EXC,FAST,FTNT,GEHC,GILD,GFS,HON,IDXX,ILMN,INTC,INTU,ISRG,KDP,KLAC,KHC,LRCX,LIN,LULU,MAR,MRVL,MELI,META,MCHP,MU,MSFT,MRNA,MDLZ,MDB,MNST,NFLX,NVDA,NXPI,ORLY,ODFL,ON,PCAR,PANW,PAYX,PYPL,PDD,PEP,QCOM,REGN,ROP,ROST,SIRI,SBUX,SNPS,TTWO,TMUS,TSLA,TXN,TTD,VRSK,VRTX,WBA,WBD,WDAY,XEL,ZS 
  - desc: SP500
    chartDataSource: SC
    category: US-INDEX
    data: MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,APD,ABNB,AKAM,ALB,ARE,ALGN,ALLE,LNT,ALL,GOOGL,GOOG,MO,AMZN,AMCR,AEE,AAL,AEP,AXP,AIG,AMT,AWK,AMP,AME,AMGN,APH,ADI,ANSS,AON,APA,AAPL,AMAT,APTV,ACGL,ADM,ANET,AJG,AIZ,T,ATO,ADSK,ADP,AZO,AVB,AVY,AXON,BKR,BALL,BAC,BK,BBWI,BAX,BDX,BRK.B,BBY,BIO,TECH,BIIB,BLK,BX,BA,BKNG,BWA,BXP,BSX,BMY,AVGO,BR,BRO,BF.B,BLDR,BG,CDNS,CZR,CPT,CPB,COF,CAH,KMX,CCL,CARR,CTLT,CAT,CBOE,CBRE,CDW,CE,COR,CNC,CNP,CF,CHRW,CRL,SCHW,CHTR,CVX,CMG,CB,CHD,CI,CINF,CTAS,CSCO,C,CFG,CLX,CME,CMS,KO,CTSH,CL,CMCSA,CMA,CAG,COP,ED,STZ,CEG,COO,CPRT,GLW,CPAY,CTVA,CSGP,COST,CTRA,CCI,CSX,CMI,CVS,DHR,DRI,DVA,DAY,DECK,DE,DAL,DVN,DXCM,FANG,DLR,DFS,DG,DLTR,D,DPZ,DOV,DOW,DHI,DTE,DUK,DD,EMN,ETN,EBAY,ECL,EIX,EW,EA,ELV,LLY,EMR,ENPH,ETR,EOG,EPAM,EQT,EFX,EQIX,EQR,ESS,EL,ETSY,EG,EVRG,ES,EXC,EXPE,EXPD,EXR,XOM,FFIV,FDS,FICO,FAST,FRT,FDX,FIS,FITB,FSLR,FE,FI,FMC,F,FTNT,FTV,FOXA,FOX,BEN,FCX,GRMN,IT,GE,GEHC,GEV,GEN,GNRC,GD,GIS,GM,GPC,GILD,GPN,GL,GS,HAL,HIG,HAS,HCA,DOC,HSIC,HSY,HES,HPE,HLT,HOLX,HD,HON,HRL,HST,HWM,HPQ,HUBB,HUM,HBAN,HII,IBM,IEX,IDXX,ITW,ILMN,INCY,IR,PODD,INTC,ICE,IFF,IP,IPG,INTU,ISRG,IVZ,INVH,IQV,IRM,JBHT,JBL,JKHY,J,JNJ,JCI,JPM,JNPR,K,KVUE,KDP,KEY,KEYS,KMB,KIM,KMI,KLAC,KHC,KR,LHX,LH,LRCX,LW,LVS,LDOS,LEN,LIN,LYV,LKQ,LMT,L,LOW,LULU,LYB,MTB,MRO,MPC,MKTX,MAR,MMC,MLM,MAS,MA,MTCH,MKC,MCD,MCK,MDT,MRK,META,MET,MTD,MGM,MCHP,MU,MSFT,MAA,MRNA,MHK,MOH,TAP,MDLZ,MPWR,MNST,MCO,MS,MOS,MSI,MSCI,NDAQ,NTAP,NFLX,NEM,NWSA,NWS,NEE,NKE,NI,NDSN,NSC,NTRS,NOC,NCLH,NRG,NUE,NVDA,NVR,NXPI,ORLY,OXY,ODFL,OMC,ON,OKE,ORCL,OTIS,PCAR,PKG,PANW,PARA,PH,PAYX,PAYC,PYPL,PNR,PEP,PFE,PCG,PM,PSX,PNW,PNC,POOL,PPG,PPL,PFG,PG,PGR,PLD,PRU,PEG,PTC,PSA,PHM,QRVO,PWR,QCOM,DGX,RL,RJF,RTX,O,REG,REGN,RF,RSG,RMD,RVTY,RHI,ROK,ROL,ROP,ROST,RCL,SPGI,CRM,SBAC,SLB,STX,SRE,NOW,SHW,SPG,SWKS,SJM,SNA,SOLV,SO,LUV,SWK,SBUX,STT,STLD,STE,SYK,SMCI,SYF,SNPS,SYY,TMUS,TROW,TTWO,TPR,TRGP,TGT,TEL,TDY,TFX,TER,TSLA,TXN,TXT,TMO,TJX,TSCO,TT,TDG,TRV,TRMB,TFC,TYL,TSN,USB,UBER,UDR,ULTA,UNP,UAL,UPS,URI,UNH,UHS,VLO,VTR,VLTO,VRSN,VRSK,VZ,VRTX,VTRS,VICI,V,VST,VMC,WRB,GWW,WAB,WBA,WMT,DIS,WBD,WM,WAT,WEC,WFC,WELL,WST,WDC,WRK,WY,WMB,WTW,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
    #
    # ROUTINE LIST
    #
  - desc: ROUTINE-ETF
    chartDataSource: SC
    category: US-ROUTINE
    data: AIQ,BLOK,BOTZ,CIBR,COPX,GDX,IBB,IGV,IHI,ITA,KBWB,KWEB,NLR,PAVE,SMH,TAN,TLT,URA,VNQ,XHB,XLY,XRT,HYG,BKCH,KIE
  - desc: ROUTINE-NON-TECH
    chartDataSource: SC
    category: US-ROUTINE
    data: BA,BAC,CAT,COST,F,GE,GS,HD,JPM,KO,MA,MCD,MMM,NOW,PG,SHW,UNH,XOM,OXY,V
  - desc: ROUTINE-TECH
    chartDataSource: SC
    category: US-ROUTINE
    data: AAPL,ADBE,AMZN,AMD,AVGO,CRM,GOOGL,IBM,META,MSFT,NFLX,Now,NVDA,SHOP,TSLA
    #
    # AI THEME
    #    
  - desc: SEMI
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: AMAT,AMD,ARM,ASML,AVGO,CDNS,ENTG,KLAC,LRCX,MCHP,MKSI,MPWR,MRVL,MU,NVDA,NXPI,QCOM,SNPS,TER,TSM,TXN
  - desc: NETWORK
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: ANET,APH,COHR,FLEX,JNPR,NTAP,TEL
  - desc: COMP-HW
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: DELL,HPE,HPQ,NTAP,PSTG,SMCI,STX,wDC
  - desc: ROBOTICS
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: CGNX,HON,ISRG,PRCT,ROK,SYK,SYM,AMZN,TSLA
  - desc: COOLING
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: CARR,FIX,GTES,IR,LII,LMB,MOD,VRT
  - desc: POWER
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: AEP,BE,CEG,D,DUK,EME,ETN,FLEX,GEV,HUBB,NEE,NRG,NVT,POWL,PWR,SO,SRE,VST
  - desc: ALT-ENERGY
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: CCJ,DNN,ENPH,FSLR,NXT
  - desc: WATER-SUPPLY
    chartDataSource: SC
    category: US-AI-ROUTINE
    data: AWK,DHR,ECL,TMO,XYL
  - desc: COPPER
    chartDataSource: SC
    category: US-AI-ROUTINE 
    data: FCX,HBM,SCCO,TECK
  - desc: SOFTWARE
    chartDataSource: SC
    category: US-AI-ROUTINE   
    data: ADSK,APP,CDNS,CFLT,CRWD,CVLT,CYBR,ESTC,FICO,IOT,MNDY,MSFT,ORCL,PANW,PLTR,SAP,SNPS,TTD,WDAY,ZS
  - desc: APPLE-AI
    chartDataSource: SC
    category: US-AI-ROUTINE 
    data: AAPL,ARM,ASX,AVGO,CRUS,GLW,MU,QCOM,QRVO,SWKS,TSM,TXN
    #
    # US-OTHER-ROUTINE
    #
  - desc: CRYPTO
    chartDataSource: SC
    category: US-OTHER-ROUTINE 
    data: CLSK,COIN,HOOD,MARA,MSTR,CIFR,WULF
  - desc: SHIPPING
    chartDataSource: SC
    category: US-OTHER-ROUTINE 
    data: ZIM,CMRE,FRO,GOGL,INSW,LPG,MATX,SBLK,TNK,ODFL
  - desc: 未來股王
    chartDataSource: SC
    category: US-OTHER-ROUTINE 
    data: TosT,oxy,snow,CFLT,ENPH,NU,S,LSCC,MNDY,sHoP,CELH,CRWD,NET,PLTR,AFRM,BNTX,DDOG,DLO,GLBE,GTLB,HUBS,LILM,OKTA,TWLO,AAPL,TSLA,MSFT,SQ
  - desc: CHINA-HK
    chartDataSource: SC
    category: US-OTHER-ROUTINE 
    data: BABA,NTES,JD,TCOM,BIDU,PUK,TME,LI,BEKE,ZTO,EDU,YUMC,HTHT,NIO,FUTU,YMM,BZ,XPEV,VIPS,BILI,TAL,MNSO,IQ,ATHM,MLCO,QFIN,HCM,RLX,LU,SIMO,ZKH,ATAT,HPH,KWEB
  - desc: WEED
    chartDataSource: SC
    category: US-OTHER-ROUTINE 
    data: TLRY,CRON,CGC,SNDL,ACB
  - desc: 基金持有的小型股
    chartDataSource: SC
    category: US-OTHER-ROUTINE 
    data: ONTO,MTDR,MOD,HQY,LNTH,RUSHA,FN,FIX,AZEK,ATKR
    #
    # MARKET-LIST
    #
  - desc: Commodity-ETF
    chartDataSource: SC
    category: MARKET-LIST 
    data: CTA,SLV,CEF,$CRB,DJP,GDX,LAND,XME,URA,$WTIC,XLE,MOO,COPX
  - desc: US-Market-ETF
    chartDataSource: SC
    category: MARKET-LIST 
    data: XLK,XLP,ARKK,SPMO,VOO,MTUM,EQAL,VYM,IWM,XMMO,XLF,BRK/B,SPHB,SPYV
  - desc: World-Market-ETF
    chartDataSource: SC
    category: MARKET-LIST 
    data: $TWII,$MERV,$NIKK,$HSI,$DAX,ASHR,$SPUK,$BVSP,$CAC,$NIFTY,$KOSPI
  - desc: Asia-Market-ETF
    chartDataSource: SC
    category: MARKET-LIST 
    data: EWJV,EWT,INDA,VNM,AVDV,SMIN,IEMG,EWZ,KWEB,IDOG,EIDO,EWW
  - desc: Currency
    chartDataSource: SC
    category: MARKET-LIST
    data: $XDN,$XDA,$XDB,SZAR,$XDC,$XDE,$XDS,$USDSEK,$USD,UUP,$USDJPY

    #
    # US-SECTOR
    #
  - desc: BOND-YIELD
    chartDataSource: SC
    category: US-SECTOR
    data: $UST7Y,$UST6M,$UST5Y,$UST3Y,$UST3M,$UST30Y,$UST2Y,$UST20Y,$UST1Y,$UST1M,$UST10Y,$USB
  - desc: SECTOR
    chartDataSource: SC
    category: US-SECTOR
    data: XLY,XLC,XLK,XLI,XLB,XLE,XLP,XLV,XLU,XLF,XLRE
  - desc: EQUAL-WEIGHT
    chartDataSource: SC
    category: US-SECTOR
    data: RSP,RSPC,RSPD,RSPS,RSPG,RSPF,RSPH,RSPN,RSPM,RSPR,RSPT,RSPU
  - desc: SECTOR-AND-EQUAL
    chartDataSource: SC
    category: US-SECTOR
    data: XLY,XLC,XLK,XLI,XLB,XLE,XLP,XLV,XLU,XLF,XLRE,RSP,RSPC,RSPD,RSPS,RSPG,RSPF,RSPH,RSPN,RSPM,RSPR,RSPT,RSPU
  - desc: CRYPTO-CURRENCY
    chartDataSource: SC
    category: US-SECTOR
    data: $BTCUSD,$ETHUSD,$XRPUSD,$BCHUSD,$USDTUSD,$LTCUSD,$BNBUSD,$LINKUSD,$TRXUSD,$XLMUSD,$XMRUSD,$DOGEUSD
    #
    # HK-THEME
    #
  - desc: 港股活躍股票
    chartDataSource: HK
    category: HK-THEME
    data: 0941.HK,0700.HK,0939.HK,0883.HK,1211.HK,2020.HK,2018.HK,1088.HK,2057.HK,1929.HK,0016.HK,9633.HK,1698.HK,0293.HK,0002.HK,0066.HK,6160.HK,0267.HK,1299.HK,0388.HK,9988.HK,9961.HK,3311.HK,1398.HK,3988.HK,3968.HK,2328.HK,2057.HK,9618.HK,9987.HK,0780.HK
  - desc: 港股人工智能股票
    chartDataSource: HK
    category: HK-THEME
    data: 0992.HK,1797.HK,1810.HK,1024.HK,9999.HK,2015.HK,9868.HK,1729.HK,0285.HK,6088.HK,2018.HK,9698.HK,9911.HK,0763.HK,1478.HK,1415.HK,0020.HK,0189.HK
  - desc: 港股指數成份
    chartDataSource: HK
    category: HK-THEME
    data: 0001.HK,0002.HK,0003.HK,0005.HK,0006.HK,0011.HK,0012.HK,0016.HK,0017.HK,0027.HK,0066.HK,0101.HK,0175.HK,0241.HK,0267.HK,0285.HK,0288.HK,0291.HK,0316.HK,0322.HK,0386.HK,0388.HK,0669.HK,0688.HK,0700.HK,0762.HK,0823.HK,0836.HK,0857.HK,0868.HK,0881.HK,0883.HK,0939.HK,0941.HK,0960.HK,0968.HK,0981.HK,0992.HK,1038.HK,1044.HK,1088.HK,1093.HK,1099.HK,1109.HK,1113.HK,1177.HK,1209.HK,1211.HK,1299.HK,1378.HK,1398.HK,1810.HK,1876.HK,1928.HK,1929.HK,1997.HK,2015.HK,2020.HK,2269.HK,2313.HK,2318.HK,2319.HK,2331.HK,2359.HK,2382.HK,2388.HK,2628.HK,2688.HK,2899.HK,3690.HK,3692.HK,3968.HK,3988.HK,6618.HK,6690.HK,6862.HK,9618.HK,9633.HK,9888.HK,9961.HK,9988.HK,9999.HK
  - desc: 港股生物科技
    chartDataSource: HK
    category: HK-THEME
    data: 0013.HK,0241.HK,0460.HK,0853.HK,0867.HK,1066.HK,1093.HK,1099.HK,1177.HK,1244.HK,1513.HK,1530.HK,1548.HK,1789.HK,1801.HK,1951.HK,1952.HK,2005.HK,2096.HK,2157.HK,2162.HK,2171.HK,2172.HK,2186.HK,2196.HK,2252.HK,2268.HK,2269.HK,2291.HK,2359.HK,2367.HK,2607.HK,3320.HK,3347.HK,3692.HK,3759.HK,3933.HK,6160.HK,6606.HK,6618.HK,6660.HK,6855.HK,6955.HK,6990.HK,9688.HK,9885.HK,9926.HK,9966.HK,9969.HK,9995.HK
  - desc: 港股科技指數
    chartDataSource: HK
    category: HK-THEME
    data: 0020.HK,0241.HK,0268.HK,0285.HK,0700.HK,0772.HK,0780.HK,0981.HK,0992.HK,1024.HK,1347.HK,1797.HK,1810.HK,1833.HK,2015.HK,2382.HK,3690.HK,3888.HK,6060.HK,6618.HK,6690.HK,9618.HK,9626.HK,9866.HK,9868.HK,9888.HK,9898.HK,9961.HK,9988.HK,9999.HK
    #
    # MARKET-BREADTH
    #
  - desc: MARKET-BREATH
    chartDataSource: SC
    category: MARKET
    data: $NAA20R,$NAA50R,$NAA200R,$SPXA20R,$SPXA50R,$SPXA200R,$DOWA20R,$DOWA50R,$DOWA200R