---
# 
company: spacelift

# Market breadth reader
stockList:
  - name: hkex
    desc: Hong Kong Stock Exchange
    link: https://www.hkex.com.hk/eng/services/trading/securities/securitieslists/ListOfSecurities.xlsx

# Indexs / exchanges / portfolios / sectors / themes
indexes:
  - name: IXIC
    breadth: $NAA20R,$NAA50R,$NAA150R,$NAA200R
    stockCode: $COMPQ
    tradingViewCode: NDX
  - name: DJI
    breadth: $DOWA20R,$DOWA50R,$DOWA150R,$DOWA200R
    stockCode: $INDU
    tradingViewCode: DJI
  - name: GSPC
    breadth: $SPXA20R,$SPXA50R,$SPXA150R,$SPXA200R
    stockCode: $SPX
    tradingViewCode: SPX

exchanges:
  - name: NIM
    tradingView: NASDAQ
  - name: PCX
    tradingView: AMEX
  - name: NYQ
    tradingView: NYSE
  - name: NMS
    tradingView: NASDAQ
  - name: NGM
    tradingView: NASDAQ
  - name: BTS
    tradingView: AMEX
  - name: DJI
    tradingView: TVC
  - name: SNP
    tradingView: TVC